import jsPDF from "jspdf";

const money = (n) => `PKR ${Number(n || 0).toLocaleString()}`;

const header = (doc, title, subtitle) => {
  doc.setFontSize(18);
  doc.text("Family Dental Clinic", 105, 18, { align: "center" });

  doc.setFontSize(11);
  doc.text("Harley Street, Saddar, Rawalpindi", 105, 25, { align: "center" });

  doc.setDrawColor(220);
  doc.line(15, 30, 195, 30);

  doc.setFontSize(14);
  doc.text(title, 15, 40);

  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text(subtitle || "", 15, 46);

  doc.setTextColor(0);
};

const tableHeader = (doc, cols, y) => {
  doc.setFontSize(10);
  doc.setDrawColor(230);
  doc.setFillColor(245, 245, 245);
  doc.rect(15, y - 5, 180, 8, "F");
  cols.forEach((c) => doc.text(c.text, c.x, y));
  doc.line(15, y + 1, 195, y + 1);
};

export const exportOwnerBillingPdf = ({
  tab,
  filters,
  rows,
  totals,
}) => {
  const doc = new jsPDF("p", "mm", "a4");

  const today = new Date().toLocaleDateString();

  const titleMap = {
    cashbook: "Daily Cashbook Report",
    revenue: "Revenue Report",
    commissions: "Commissions Report",
    labDues: "Lab Dues Report",
  };

  header(
    doc,
    titleMap[tab] || "Financial Report",
    `Generated: ${today}`
  );

  let y = 58;

  // Filters summary line
  doc.setFontSize(10);
  doc.setTextColor(90);

  const f = filters || {};
  const filterText = Object.entries(f)
    .filter(([, v]) => v && v !== "all")
    .map(([k, v]) => `${k}: ${v}`)
    .join("   |   ");

  doc.text(filterText || "Filters: (none)", 15, 54);
  doc.setTextColor(0);

  const nextY = (inc = 7) => {
    y += inc;
    if (y > 270) {
      doc.addPage();
      y = 25;
    }
  };

  // Render table based on tab
  if (tab === "cashbook") {
    const cols = [
      { text: "Date", x: 15 },
      { text: "Cash", x: 80 },
      { text: "Card", x: 120 },
      { text: "Total", x: 160 },
    ];
    tableHeader(doc, cols, y);
    nextY(8);

    rows.forEach((r) => {
      doc.text(String(r.date), 15, y);
      doc.text(money(r.cash), 80, y);
      doc.text(money(r.card), 120, y);
      doc.text(money(r.cash + r.card), 160, y);
      nextY(7);
    });

    nextY(6);
    doc.setFontSize(11);
    doc.text(`Total Cash: ${money(totals?.a)}`, 15, y);
    nextY(6);
    doc.text(`Total Card: ${money(totals?.b)}`, 15, y);
    nextY(6);
    doc.text(`Grand Total: ${money(totals?.total)}`, 15, y);
  }

  if (tab === "revenue") {
    const cols = [
      { text: "Date", x: 15 },
      { text: "Dentist", x: 60 },
      { text: "Method", x: 125 },
      { text: "Amount", x: 160 },
    ];
    tableHeader(doc, cols, y);
    nextY(8);

    rows.forEach((r) => {
      doc.text(String(r.date), 15, y);
      doc.text(String(r.dentistName), 60, y);
      doc.text(String(r.method), 125, y);
      doc.text(money(r.amount), 160, y);
      nextY(7);
    });

    nextY(6);
    doc.setFontSize(11);
    doc.text(`Total Revenue: ${money(totals?.total)}`, 15, y);
  }

  if (tab === "commissions") {
    const cols = [
      { text: "Dentist", x: 15 },
      { text: "Revenue", x: 85 },
      { text: "%", x: 135 },
      { text: "Commission", x: 160 },
    ];
    tableHeader(doc, cols, y);
    nextY(8);

    rows.forEach((r) => {
      doc.text(String(r.dentistName), 15, y);
      doc.text(money(r.revenue), 85, y);
      doc.text(`${r.percent}%`, 135, y);
      doc.text(money(r.commission), 160, y);
      nextY(7);
    });

    nextY(6);
    doc.setFontSize(11);
    doc.text(`Total Revenue: ${money(totals?.revenue)}`, 15, y);
    nextY(6);
    doc.text(`Total Commission Payout: ${money(totals?.payout)}`, 15, y);
  }

  if (tab === "labDues") {
    const cols = [
      { text: "Lab", x: 15 },
      { text: "Month", x: 110 },
      { text: "Amount", x: 160 },
    ];
    tableHeader(doc, cols, y);
    nextY(8);

    rows.forEach((r) => {
      doc.text(String(r.labName), 15, y);
      doc.text(String(r.month), 110, y);
      doc.text(money(r.amount), 160, y);
      nextY(7);
    });

    nextY(6);
    doc.setFontSize(11);
    doc.text(`Total Lab Dues: ${money(totals?.total)}`, 15, y);
  }

  // Footer
  doc.setDrawColor(220);
  doc.line(15, 282, 195, 282);
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text("Generated by Dental Clinic Management Portal", 15, 288);

  doc.save(`Owner_Report_${tab}_${new Date().toISOString().slice(0, 10)}.pdf`);
};